name: build-flutter-apk
displayName: Flutter计分器APK构建
triggers:
  push:
    branches:
      include:
        - master
jobs:
  job:
    stage:
      name: build
      displayName: 构建APK
      runs-on: ubuntu-latest
      steps:
        - step:
            name: 检出代码
            uses: checkout@v3
        - step:
            name: 安装依赖
            run: flutter pub get
        - step:
            name: 构建APK
            run: flutter build apk --release
        - step:
            name: 上传APK
            uses: artifact@v1
            with:
              name: release-apk
              path: build/app/outputs/flutter-apk/app-release.apk
